module.exports = [
  {
    date: 'Jun 11, 2024',
    location: 'Austin, Texas',
    venue: 'Zilker Park',
    description: 'Digital Dreamscape Festival',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jun 24, 2024',
    location: 'Austin, Texas',
    venue: 'Emos East',
    description: 'Album Release Party',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jun 27, 2024',
    location: 'Luckenbach, Texas',
    venue: 'Luckenbach Dance Hall',
    description: 'Live at Historic Luckenback',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jun 29, 2024',
    location: 'Terlingua, Texas',
    venue: 'Starlight Theatre',
    description: 'Live in The Desert',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 3, 2024',
    location: 'Albuquerque, New Mexico',
    venue: 'Albuquerque Convention Center',
    description: 'Developer Conference',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 7, 2024',
    location: 'Los Angeles, California',
    venue: 'Viper Room',
    description: 'Retro Night',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 9, 2024',
    location: 'Los Angeles, California',
    venue: 'Dodger Stadium',
    description: 'Post Game Concert',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 13, 2024',
    location: 'Dufur, Oregon',
    venue: 'Wolf Run Ranch',
    description: 'What The Festival',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 20, 2024',
    location: 'Portland, Oregon',
    venue: 'The Fields Park',
    description: 'Portland Craft Beer Festival',
    ticket: 'https://frontgatetickets.com',
  },
  {
    date: 'Jul 21, 2024',
    location: 'Seattle, Washington',
    venue: 'Bite of Seattle',
    description: 'Bite of Seattle Food and Musical Festival',
    ticket: 'https://frontgatetickets.com',
  },
];
